### ISSUE TITLE
output unexpected

### ISSUE THREAD

**Issue by SubarnaKhadka** [Ayu-99/Data-Structures#6]
Output unexpected 
on 
Data-Structures/Leetcode Challenge/May/C++/Remove All Adjacent Duplicates in String II.cpp  
![leetcodeError](https://user-images.githubusercontent.com/90277365/167160725-96b3c497-2bb5-45a5-abb0-9131af7aa386.PNG)

**Comment by shubham-mishra06** [comment]
just reverse the string u will get desired output

**Comment by SubarnaKhadka** [comment]
Yeah, Need to add 
reverse( ans.begin() ,ans.end() );
before  
return ans;
